version: '3'
services:
  redis:
    image: redis:6
    ports:
      - 6379:6379   
  centrifugo:
    image: centrifugo/centrifugo:v3.0.5
    volumes:
      - ./conf/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8001:8001
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - redis
  app:
    build:
      context: ./mysite
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '9000:9000'
    command: 'bash -c "nginx -g ''daemon off;''"'
    depends_on:
      - centrifugo
      - app
