services:
  centrifugo:
    image: centrifugo/centrifugo:v6
    container_name: centrifugo
    ports:
      - "8000:8000"
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo -c /centrifugo/config.json
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - centrifugo
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - centrifugo