// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proxystreamproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CentrifugoProxyStreamClient is the client API for CentrifugoProxyStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CentrifugoProxyStreamClient interface {
	SubscribeStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (CentrifugoProxyStream_SubscribeStreamClient, error)
}

type centrifugoProxyStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewCentrifugoProxyStreamClient(cc grpc.ClientConnInterface) CentrifugoProxyStreamClient {
	return &centrifugoProxyStreamClient{cc}
}

func (c *centrifugoProxyStreamClient) SubscribeStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (CentrifugoProxyStream_SubscribeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &CentrifugoProxyStream_ServiceDesc.Streams[0], "/centrifugal.centrifugo.proxystream.CentrifugoProxyStream/SubscribeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &centrifugoProxyStreamSubscribeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CentrifugoProxyStream_SubscribeStreamClient interface {
	Recv() (*Publication, error)
	grpc.ClientStream
}

type centrifugoProxyStreamSubscribeStreamClient struct {
	grpc.ClientStream
}

func (x *centrifugoProxyStreamSubscribeStreamClient) Recv() (*Publication, error) {
	m := new(Publication)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CentrifugoProxyStreamServer is the server API for CentrifugoProxyStream service.
// All implementations must embed UnimplementedCentrifugoProxyStreamServer
// for forward compatibility
type CentrifugoProxyStreamServer interface {
	SubscribeStream(*SubscribeStreamRequest, CentrifugoProxyStream_SubscribeStreamServer) error
	mustEmbedUnimplementedCentrifugoProxyStreamServer()
}

// UnimplementedCentrifugoProxyStreamServer must be embedded to have forward compatible implementations.
type UnimplementedCentrifugoProxyStreamServer struct {
}

func (UnimplementedCentrifugoProxyStreamServer) SubscribeStream(*SubscribeStreamRequest, CentrifugoProxyStream_SubscribeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeStream not implemented")
}
func (UnimplementedCentrifugoProxyStreamServer) mustEmbedUnimplementedCentrifugoProxyStreamServer() {}

// UnsafeCentrifugoProxyStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CentrifugoProxyStreamServer will
// result in compilation errors.
type UnsafeCentrifugoProxyStreamServer interface {
	mustEmbedUnimplementedCentrifugoProxyStreamServer()
}

func RegisterCentrifugoProxyStreamServer(s grpc.ServiceRegistrar, srv CentrifugoProxyStreamServer) {
	s.RegisterService(&CentrifugoProxyStream_ServiceDesc, srv)
}

func _CentrifugoProxyStream_SubscribeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CentrifugoProxyStreamServer).SubscribeStream(m, &centrifugoProxyStreamSubscribeStreamServer{stream})
}

type CentrifugoProxyStream_SubscribeStreamServer interface {
	Send(*Publication) error
	grpc.ServerStream
}

type centrifugoProxyStreamSubscribeStreamServer struct {
	grpc.ServerStream
}

func (x *centrifugoProxyStreamSubscribeStreamServer) Send(m *Publication) error {
	return x.ServerStream.SendMsg(m)
}

// CentrifugoProxyStream_ServiceDesc is the grpc.ServiceDesc for CentrifugoProxyStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CentrifugoProxyStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "centrifugal.centrifugo.proxystream.CentrifugoProxyStream",
	HandlerType: (*CentrifugoProxyStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeStream",
			Handler:       _CentrifugoProxyStream_SubscribeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proxystream.proto",
}
