version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # centrifugo:
  #   image: centrifugo/centrifugo:v6
  #   volumes:
  #     - ./centrifugo/config.json:/centrifugo/config.json
  #   command: centrifugo --config=/centrifugo/config.json
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     redis:
  #       condition: service_started

  backend:
    build: ./backend
    depends_on:
      redis:
        condition: service_started
      # centrifugo:
      #   condition: service_started

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_started
      web:
        condition: service_started

  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
